"""empty message

Revision ID: 6c07d5446753
Revises: 
Create Date: 2022-11-23 16:17:27.662788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c07d5446753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talonario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('premio', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Float(precision=10), nullable=False),
    sa.Column('imagen_premio', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('fecha_sorteo', sa.Date(), nullable=False),
    sa.Column('plataforma_sorteo', sa.String(length=100), nullable=False),
    sa.Column('metodo_de_pago', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('talonario_id', sa.Integer(), nullable=True),
    sa.Column('user_ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talonario_id'], ['talonario.id'], ),
    sa.ForeignKeyConstraint(['user_ticket_id'], ['user_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('talonario')
    op.drop_table('user_ticket')
    op.drop_table('user')
    # ### end Alembic commands ###
